[package]
name = "luedd-core"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
thiserror.workspace = true
async-trait.workspace = true
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true
futures.workspace = true
chrono.workspace = true
uuid = { version = "1", features = ["v4"] }
url.workspace = true
luedd-net = { path = "../luedd-net" }
luedd-media = { path = "../luedd-media" }
