[package]
name = "tidm-core"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
thiserror.workspace = true
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true
futures.workspace = true
chrono.workspace = true
uuid = { version = "1", features = ["v4"] }
tidm-net = { path = "../tidm-net" }
tidm-media = { path = "../tidm-media" }
