[package]
name = "tidm-cli"
version.workspace = true
edition.workspace = true

[[bin]]
name = "tidm-cli"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
tokio.workspace = true
url.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
tidm-net = { path = "../tidm-net" }
tidm-media = { path = "../tidm-media" }
tidm-core = { path = "../tidm-core" }
tidm-ipc = { path = "../tidm-ipc" }
